name: Release

on:
  push:
    branches: [production]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18.20.8
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Type checking
        run: bun run type-check

      - name: Build
        run: bun run build

      - name: Tests
        run: bun test

      - name: Publish to NPM
        run: bun run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
